version: "3"
services:
  node-app:
    build: .
    ports:
      - "3001:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    # environment:
    #   PORT=3002
    env_file:
      - ./.env
    